# 1 restaurant and all their reviews

SELECT *
WHERE 
{
    SERVICE <http://192.168.60.113/jena/fuseki/yelp/sparql>
    { 
        SELECT *
        WHERE {
                {
                    ?s a <https://myontology.com#business>;
                    <https://myontology.com#business_id> "buF9druCkbuXLX526sGELQ" ;
                    <https://myontology.com#business_id> ?business_id;
                    <https://myontology.com#address> ?address; 
                    <https://myontology.com#city> ?city;   
                    <https://myontology.com#name> ?name .
                    # ?s ?p ?v.  
                }
            # UNION {
            #     ?r a <https://myontology.com#review>;
            #     <https://myontology.com#business_id> "buF9druCkbuXLX526sGELQ" ;
            #     <https://myontology.com#review_id> ?review_id .
            # } 

        } 

    }
}


# all restaurants and their reviews



# arq -query 
# buF9druCkbuXLX526sGELQ