SELECT *
WHERE 
{
    SERVICE <http://192.168.60.113/jena/fuseki/yeld_b_r/sparql>
    { 
        SELECT ?user_id ?review_date ?b_id ?b_id2 ?b_name # ?b_id ?review_id ?user_id
        WHERE {
                {
                    ?r a <https://myontology.com#review>;
                    # <https://myontology.com#business_id> ?b_id ;
                    <https://myontology.com#user_id> ?user_id ;
                    <https://myontology.com#review_id> ?review_id ;
                    <https://myontology.com#date> ?review_date ;
                    <https://myontology.com#business_id> ?b_id .                    
                }
                {
                   ?b a <https://myontology.com#business>;
                      <https://myontology.com#business_id> ?b_id;
                      <https://myontology.com#business_id> ?b_id2;
                      <https://myontology.com#name> ?b_name
                       .                    

                }
        }
    }
}
# what are the businesses with reviews?
# and what other business did those users review